#!/usr/bin/env python3
"""
TvFruit — Local obfuscator / build tool.

Workflow:
  - READABLE source lives in src/   (edit here)
  - Run: python build.py
  - OBFUSCATED output is written to games/  (the router loads these)

Basic obfuscation: encrypt the whole file (multi-byte XOR + \\ddd escape),
wrap it in a loadstring loader. Output is not human-readable but runs
unchanged in Delta. NOT as strong as paid VM obfuscators — enough to deter
casual source copying.

theme.lua (games/lib) and TvFruit.lua (router) stay READABLE: they are the
shared framework + entry point and must run / be fetched directly.
"""
import random, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC  = ROOT / "src"
OUT  = ROOT / "games"

# game files to obfuscate: src/<name> -> games/<name>
TARGETS = ["grow_a_garden.lua", "speed_escape.lua"]


def obfuscate(src_text: str) -> str:
    data = src_text.encode("utf-8")
    klen = random.randint(8, 16)
    key  = [random.randint(1, 255) for _ in range(klen)]
    enc  = bytes(b ^ key[i % klen] for i, b in enumerate(data))

    # self-check: decoding must match the original source
    dec = bytes(enc[i] ^ key[i % klen] for i in range(len(enc)))
    assert dec == data, "roundtrip mismatch — build aborted"

    enc_str = "".join("\\%03d" % b for b in enc)   # each byte as a \ddd escape (3 digits, unambiguous)
    key_str = ",".join(map(str, key))
    rnd = lambda: "_" + "".join(random.choice("lI1") for _ in range(7))
    K, D, O, I = rnd(), rnd(), rnd(), rnd()

    return (
        "-- TvFruit obfuscated build | DO NOT edit this file.\n"
        "-- Edit the readable source in src/ then run: python build.py\n"
        f"local {K}={{{key_str}}}\n"
        f'local {D}="{enc_str}"\n'
        f"local {O}={{}}\n"
        f"for {I}=1,#{D} do {O}[{I}]=string.char(bit32.bxor(string.byte({D},{I}),{K}[(({I}-1)%#{K})+1]))end\n"
        f"return assert(loadstring(table.concat({O})))()\n"
    )


def main():
    if not SRC.exists():
        print("src/ folder not found"); sys.exit(1)
    OUT.mkdir(exist_ok=True)
    for name in TARGETS:
        src_path = SRC / name
        if not src_path.exists():
            print(f"[skip] missing src/{name}"); continue
        s = src_path.read_text(encoding="utf-8")
        o = obfuscate(s)
        (OUT / name).write_text(o, encoding="utf-8")
        print(f"[build] {name}: {len(s)} -> {len(o)} bytes (obfuscated OK)")
    print("Done. games/ updated with obfuscated builds.")


if __name__ == "__main__":
    main()
